Deps: Update faithfuls <easy-as-pypi>
- Source: easy-as-pypi @ 350aee09df60 [1.1.11a7~42]

- Commit generated by:

    https://github.com/thegittinsgood/git-update-faithful#⛲

  under the guidance of:

    https://github.com/doblabs/easy-as-pypi/blob/release/bin/update-faithful

diff --git a/.github/workflows/release-github.yml b/.github/workflows/release-github.yml
--- a/.github/workflows/release-github.yml
+++ b/.github/workflows/release-github.yml
@@ -69,17 +69,24 @@ jobs:
         shell: bash
 
       - name: Check if prerelease
+        id: check-if-prerelease
         # Note the v?: Don't care!
         run: |
-          echo "$VERSION_TAG" | grep -q -E -e "^v?[0-9]+\.[0-9]+\.[0-9]+$" \
-            || echo "PRERELEASE=--prerelease" >> "$GITHUB_ENV"
+          is_prerelease=false
+          if ! echo "${VERSION_TAG}" \
+            | grep -q -E -e "^v?[0-9]+\.[0-9]+\.[0-9]+$" \
+          ; then
+            is_prerelease=true
+            echo "PRERELEASE=--prerelease" >> "${GITHUB_ENV}"
+          fi
+          echo "is_prerelease=${is_prerelease}" >> "${GITHUB_OUTPUT}"
 
       - name: Announcement
         run: |
           [ -z "${PRERELEASE}" ] \
             && prerelease_msg="" \
             || prerelease_msg=" (prerelease)"
-          echo "Processing $VERSION_TAG tag${prerelease_msg}"
+          echo "Processing ${VERSION_TAG} tag${prerelease_msg}"
 
       # ***
 
@@ -92,14 +99,35 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.repository.default_branch }}
+          # If pre-release, use alternative branch if defined.
+          ref: ${{
+            steps.check-if-prerelease.outputs.is_prerelease == 'true'
+            && vars.PRERELEASE_BRANCH
+            || github.event.repository.default_branch }}
           # Fetch all history, so rev-parse HEAD is real HEAD.
           fetch-depth: 0
 
-      # Compare default branch HEAD and workflow event GITHUB_SHA.
-      - name: Verify default branch HEAD is what was tagged
+      # Fail workflow unless workflow event GITHUB_SHA matches branch HEAD.
+      # - Note that, sure, the user might have pushed more commits to HEAD
+      #   since they version-tagged. So maybe that's a legit use case, and
+      #   this check is overkill. And maybe someday we'll disable this check.
+      #   - But until that day when this check actually annoys you, leave it.
+      - name: Verify branch HEAD is what was tagged
         run: |
-          [ "$GITHUB_SHA" = "$(git rev-parse HEAD)" ] || exit 1
+          echo "test \"${GITHUB_SHA}\" = \"$(git rev-parse HEAD)\""
+          [ "${GITHUB_SHA}" = "$(git rev-parse HEAD)" ] || exit 1
+
+      # Similar to last check, this might be overkill, but check the version
+      # exists on the HEAD commit, too.
+      - name: Verify branch HEAD is what was versioned
+        run: |
+          head_tag_match="$(git tag --list --points-at HEAD "${VERSION_TAG}")"
+          echo "test \"${head_tag_match}\" = \"${VERSION_TAG}\""
+          ([ -n "${head_tag_match}" ] \
+           && [ "${head_tag_match}" = "${VERSION_TAG}" ] \
+          ) || exit 1
+        env:
+          VERSION_TAG: ${{ inputs.version_tag }}
 
       # ***
 
@@ -125,6 +153,56 @@ jobs:
         with:
           python-version: ${{ env.PYTHON_VERSION }}
           cache: 'poetry'
+
+      # NOICE: DRY: Use `make --eval` to add temp. make target that prints
+      # the pre-release pyproject.toml directory (avoids USYNC/hardcoding).
+      - name: Determine pyproject.toml to use (normal or alpha)
+        run: |
+          pyproject_dir="."
+          if [ "${PRERELEASE}" = "--prerelease" ]; then
+            pyproject_dir="$(
+              make \
+                --eval='print-var: ; @echo $(PYPROJECT_PRERELEASE_DIR)' \
+                print-var
+            )"
+          fi
+          echo "PYPROJECT_DIR=${pyproject_dir}" >> "${GITHUB_ENV}"
+
+      - name: Verify Poetry assets — pyproject.toml and poetry.lock
+        run: |
+          assets_exist () {
+            local pyproject_dir="${1:-.}"
+
+            [ -f "${pyproject_dir}/pyproject.toml" ] \
+            && [ -f "${pyproject_dir}/poetry.lock" ]
+          }
+
+          if [ "${PRERELEASE}" = "--prerelease" ]; then
+            if ! assets_exist "${PYPROJECT_DIR}"; then
+              >&2 echo "ERROR: Where are the ${PYPROJECT_DIR} Poetry assets?"
+              >&2 echo "- Missing pyproject.toml and/or poetry.lock"
+              >&2 echo "- HINT: Run the update-deps.yml workflow"
+              >&2 echo "  - OR: Run \`make prepare-poetry-prerelease\`"
+              >&2 echo "        and then commit the two files to the repo"
+
+              exit 1
+            fi
+          elif ! assets_exist; then
+            >&2 echo "ERROR: Missing pyproject.toml and/or poetry.lock"
+            >&2 echo "- HINT: Run the update-deps.yml workflow"
+            >&2 echo "  - OR: Run \`make install\`"
+            >&2 echo "        and then commit the lock file to the repo"
+
+            exit 1
+          fi
+
+      # Note that `poetry -C "${PYPROJECT_DIR}" build` won't work if it
+      # references anything from root, so clobber root's lock and toml.
+      - name: Prepare Pre-release Poetry assets — pyproject.toml and poetry.lock
+        if: env.PRERELEASE == '--prerelease'
+        run: |
+          command cp -f "${PYPROJECT_DIR}/poetry.lock" "poetry.lock"
+          command cp -f "${PYPROJECT_DIR}/pyproject.toml" "pyproject.toml"
 
       - name: Poetry build
         run: |
